service: users-api

frameworkVersion: "3"

custom:
  url: undefined
  force: undefined

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev

functions:
  users:
    handler: handler.users
    environment:
      DB_URL: ${self:custom.url}
      FORCE_DELETE_FIELD: ${self:custom.force}
